[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name tail
    Path /logs/app.log
    Tag app.logs
    Refresh_Interval 5

[OUTPUT]
    Name loki
    Match *
    Host loki
    Port 3100
    Labels job=go-app