[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name tail
    Path /logs/account/app.log
    Tag account.logs
    Refresh_Interval 5

[INPUT]
    Name tail
    Path /logs/transaction/app.log
    Tag transaction.logs
    Refresh_Interval 5

[INPUT]
    Name tail
    Path /logs/notification/app.log
    Tag notification.logs
    Refresh_Interval 5

[OUTPUT]
    Name loki
    Match *
    Host loki
    Port 3100
    Labels job=microservices-bank