// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package accountpb

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/runtime/protoimpl"
)

const _ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)

// ── Messages ────────────────────────────────────────────

type GetByAccountNumberRequest struct {
	AccountNumber string `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
}

type GetByIDRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

type AccountResponse struct {
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountNumber string `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountHolder string `protobuf:"bytes,3,opt,name=account_holder,json=accountHolder,proto3" json:"account_holder,omitempty"`
	Balance       int64  `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt     string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

type UpdateBalanceRequest struct {
	AccountNumber string `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Amount        int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

type UpdateBalanceResponse struct {
	Success       bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccountNumber string `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	NewBalance    int64  `protobuf:"varint,3,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

// Getter methods for GetByAccountNumberRequest
func (x *GetByAccountNumberRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *GetByAccountNumberRequest) ProtoReflect() {}
func (x *GetByAccountNumberRequest) Reset()        {}
func (x *GetByAccountNumberRequest) String() string { return x.AccountNumber }

// Getter methods for GetByIDRequest
func (x *GetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetByIDRequest) ProtoReflect() {}
func (x *GetByIDRequest) Reset()        {}
func (x *GetByIDRequest) String() string { return x.Id }

// Getter methods for AccountResponse
func (x *AccountResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *AccountResponse) GetAccountHolder() string {
	if x != nil {
		return x.AccountHolder
	}
	return ""
}

func (x *AccountResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AccountResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *AccountResponse) ProtoReflect() {}
func (x *AccountResponse) Reset()        {}
func (x *AccountResponse) String() string { return x.Id }

// Getter methods for UpdateBalanceRequest
func (x *UpdateBalanceRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *UpdateBalanceRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateBalanceRequest) ProtoReflect() {}
func (x *UpdateBalanceRequest) Reset()        {}
func (x *UpdateBalanceRequest) String() string { return x.AccountNumber }

// Getter methods for UpdateBalanceResponse
func (x *UpdateBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateBalanceResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *UpdateBalanceResponse) GetNewBalance() int64 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

func (x *UpdateBalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateBalanceResponse) ProtoReflect() {}
func (x *UpdateBalanceResponse) Reset()        {}
func (x *UpdateBalanceResponse) String() string { return x.Message }

// ── gRPC Service ────────────────────────────────────────

// AccountServiceClient is the client API for AccountService.
type AccountServiceClient interface {
	GetByAccountNumber(ctx context.Context, in *GetByAccountNumberRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	UpdateBalance(ctx context.Context, in *UpdateBalanceRequest, opts ...grpc.CallOption) (*UpdateBalanceResponse, error)
	GetByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*AccountResponse, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetByAccountNumber(ctx context.Context, in *GetByAccountNumberRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/GetByAccountNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateBalance(ctx context.Context, in *UpdateBalanceRequest, opts ...grpc.CallOption) (*UpdateBalanceResponse, error) {
	out := new(UpdateBalanceResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/UpdateBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService.
type AccountServiceServer interface {
	GetByAccountNumber(context.Context, *GetByAccountNumberRequest) (*AccountResponse, error)
	UpdateBalance(context.Context, *UpdateBalanceRequest) (*UpdateBalanceResponse, error)
	GetByID(context.Context, *GetByIDRequest) (*AccountResponse, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) GetByAccountNumber(context.Context, *GetByAccountNumberRequest) (*AccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByAccountNumber not implemented")
}

func (UnimplementedAccountServiceServer) UpdateBalance(context.Context, *UpdateBalanceRequest) (*UpdateBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBalance not implemented")
}

func (UnimplementedAccountServiceServer) GetByID(context.Context, *GetByIDRequest) (*AccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}

func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_GetByAccountNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByAccountNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetByAccountNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetByAccountNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetByAccountNumber(ctx, req.(*GetByAccountNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/UpdateBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateBalance(ctx, req.(*UpdateBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService.
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByAccountNumber",
			Handler:    _AccountService_GetByAccountNumber_Handler,
		},
		{
			MethodName: "UpdateBalance",
			Handler:    _AccountService_UpdateBalance_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _AccountService_GetByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
