// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/fraud.proto

package fraudpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FraudCheckRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SourceAccountNo      string                 `protobuf:"bytes,1,opt,name=source_account_no,json=sourceAccountNo,proto3" json:"source_account_no,omitempty"`
	BeneficiaryAccountNo string                 `protobuf:"bytes,2,opt,name=beneficiary_account_no,json=beneficiaryAccountNo,proto3" json:"beneficiary_account_no,omitempty"`
	Amount               float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	PartnerReferenceNo   string                 `protobuf:"bytes,5,opt,name=partner_reference_no,json=partnerReferenceNo,proto3" json:"partner_reference_no,omitempty"`
	TransactionDate      string                 `protobuf:"bytes,6,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FraudCheckRequest) Reset() {
	*x = FraudCheckRequest{}
	mi := &file_proto_fraud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudCheckRequest) ProtoMessage() {}

func (x *FraudCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudCheckRequest.ProtoReflect.Descriptor instead.
func (*FraudCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_fraud_proto_rawDescGZIP(), []int{0}
}

func (x *FraudCheckRequest) GetSourceAccountNo() string {
	if x != nil {
		return x.SourceAccountNo
	}
	return ""
}

func (x *FraudCheckRequest) GetBeneficiaryAccountNo() string {
	if x != nil {
		return x.BeneficiaryAccountNo
	}
	return ""
}

func (x *FraudCheckRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FraudCheckRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FraudCheckRequest) GetPartnerReferenceNo() string {
	if x != nil {
		return x.PartnerReferenceNo
	}
	return ""
}

func (x *FraudCheckRequest) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

type FraudCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`                     // true = proceed, false = reject
	FraudCode     string                 `protobuf:"bytes,2,opt,name=fraud_code,json=fraudCode,proto3" json:"fraud_code,omitempty"` // "OK" | "BLOCKED_ACCOUNT" | "VELOCITY_BREACH" | ...
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RiskLevel     string                 `protobuf:"bytes,4,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"` // "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudCheckResponse) Reset() {
	*x = FraudCheckResponse{}
	mi := &file_proto_fraud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudCheckResponse) ProtoMessage() {}

func (x *FraudCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudCheckResponse.ProtoReflect.Descriptor instead.
func (*FraudCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_fraud_proto_rawDescGZIP(), []int{1}
}

func (x *FraudCheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *FraudCheckResponse) GetFraudCode() string {
	if x != nil {
		return x.FraudCode
	}
	return ""
}

func (x *FraudCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FraudCheckResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

type BlockAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNo     string                 `protobuf:"bytes,1,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	BlockedBy     string                 `protobuf:"bytes,3,opt,name=blocked_by,json=blockedBy,proto3" json:"blocked_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockAccountRequest) Reset() {
	*x = BlockAccountRequest{}
	mi := &file_proto_fraud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockAccountRequest) ProtoMessage() {}

func (x *BlockAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockAccountRequest.ProtoReflect.Descriptor instead.
func (*BlockAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_fraud_proto_rawDescGZIP(), []int{2}
}

func (x *BlockAccountRequest) GetAccountNo() string {
	if x != nil {
		return x.AccountNo
	}
	return ""
}

func (x *BlockAccountRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BlockAccountRequest) GetBlockedBy() string {
	if x != nil {
		return x.BlockedBy
	}
	return ""
}

type BlockAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockAccountResponse) Reset() {
	*x = BlockAccountResponse{}
	mi := &file_proto_fraud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockAccountResponse) ProtoMessage() {}

func (x *BlockAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockAccountResponse.ProtoReflect.Descriptor instead.
func (*BlockAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_fraud_proto_rawDescGZIP(), []int{3}
}

func (x *BlockAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BlockAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnblockAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNo     string                 `protobuf:"bytes,1,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	UnblockedBy   string                 `protobuf:"bytes,2,opt,name=unblocked_by,json=unblockedBy,proto3" json:"unblocked_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockAccountRequest) Reset() {
	*x = UnblockAccountRequest{}
	mi := &file_proto_fraud_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockAccountRequest) ProtoMessage() {}

func (x *UnblockAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockAccountRequest.ProtoReflect.Descriptor instead.
func (*UnblockAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_fraud_proto_rawDescGZIP(), []int{4}
}

func (x *UnblockAccountRequest) GetAccountNo() string {
	if x != nil {
		return x.AccountNo
	}
	return ""
}

func (x *UnblockAccountRequest) GetUnblockedBy() string {
	if x != nil {
		return x.UnblockedBy
	}
	return ""
}

type UnblockAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockAccountResponse) Reset() {
	*x = UnblockAccountResponse{}
	mi := &file_proto_fraud_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockAccountResponse) ProtoMessage() {}

func (x *UnblockAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockAccountResponse.ProtoReflect.Descriptor instead.
func (*UnblockAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_fraud_proto_rawDescGZIP(), []int{5}
}

func (x *UnblockAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnblockAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAccountStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNo     string                 `protobuf:"bytes,1,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountStatusRequest) Reset() {
	*x = GetAccountStatusRequest{}
	mi := &file_proto_fraud_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountStatusRequest) ProtoMessage() {}

func (x *GetAccountStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAccountStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_fraud_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountStatusRequest) GetAccountNo() string {
	if x != nil {
		return x.AccountNo
	}
	return ""
}

type GetAccountStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNo     string                 `protobuf:"bytes,1,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,2,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	BlockReason   string                 `protobuf:"bytes,3,opt,name=block_reason,json=blockReason,proto3" json:"block_reason,omitempty"`
	BlockedBy     string                 `protobuf:"bytes,4,opt,name=blocked_by,json=blockedBy,proto3" json:"blocked_by,omitempty"`
	BlockedAt     string                 `protobuf:"bytes,5,opt,name=blocked_at,json=blockedAt,proto3" json:"blocked_at,omitempty"`
	VelocityCount int32                  `protobuf:"varint,6,opt,name=velocity_count,json=velocityCount,proto3" json:"velocity_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountStatusResponse) Reset() {
	*x = GetAccountStatusResponse{}
	mi := &file_proto_fraud_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountStatusResponse) ProtoMessage() {}

func (x *GetAccountStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAccountStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_fraud_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccountStatusResponse) GetAccountNo() string {
	if x != nil {
		return x.AccountNo
	}
	return ""
}

func (x *GetAccountStatusResponse) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *GetAccountStatusResponse) GetBlockReason() string {
	if x != nil {
		return x.BlockReason
	}
	return ""
}

func (x *GetAccountStatusResponse) GetBlockedBy() string {
	if x != nil {
		return x.BlockedBy
	}
	return ""
}

func (x *GetAccountStatusResponse) GetBlockedAt() string {
	if x != nil {
		return x.BlockedAt
	}
	return ""
}

func (x *GetAccountStatusResponse) GetVelocityCount() int32 {
	if x != nil {
		return x.VelocityCount
	}
	return 0
}

var File_proto_fraud_proto protoreflect.FileDescriptor

const file_proto_fraud_proto_rawDesc = "" +
	"\n" +
	"\x11proto/fraud.proto\x12\x05fraud\"\x86\x02\n" +
	"\x11FraudCheckRequest\x12*\n" +
	"\x11source_account_no\x18\x01 \x01(\tR\x0fsourceAccountNo\x124\n" +
	"\x16beneficiary_account_no\x18\x02 \x01(\tR\x14beneficiaryAccountNo\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x120\n" +
	"\x14partner_reference_no\x18\x05 \x01(\tR\x12partnerReferenceNo\x12)\n" +
	"\x10transaction_date\x18\x06 \x01(\tR\x0ftransactionDate\"\x86\x01\n" +
	"\x12FraudCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1d\n" +
	"\n" +
	"fraud_code\x18\x02 \x01(\tR\tfraudCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x04 \x01(\tR\triskLevel\"k\n" +
	"\x13BlockAccountRequest\x12\x1d\n" +
	"\n" +
	"account_no\x18\x01 \x01(\tR\taccountNo\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"blocked_by\x18\x03 \x01(\tR\tblockedBy\"J\n" +
	"\x14BlockAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Y\n" +
	"\x15UnblockAccountRequest\x12\x1d\n" +
	"\n" +
	"account_no\x18\x01 \x01(\tR\taccountNo\x12!\n" +
	"\funblocked_by\x18\x02 \x01(\tR\vunblockedBy\"L\n" +
	"\x16UnblockAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"8\n" +
	"\x17GetAccountStatusRequest\x12\x1d\n" +
	"\n" +
	"account_no\x18\x01 \x01(\tR\taccountNo\"\xe0\x01\n" +
	"\x18GetAccountStatusResponse\x12\x1d\n" +
	"\n" +
	"account_no\x18\x01 \x01(\tR\taccountNo\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x02 \x01(\bR\tisBlocked\x12!\n" +
	"\fblock_reason\x18\x03 \x01(\tR\vblockReason\x12\x1d\n" +
	"\n" +
	"blocked_by\x18\x04 \x01(\tR\tblockedBy\x12\x1d\n" +
	"\n" +
	"blocked_at\x18\x05 \x01(\tR\tblockedAt\x12%\n" +
	"\x0evelocity_count\x18\x06 \x01(\x05R\rvelocityCount2\xcd\x02\n" +
	"\x15FraudDetectionService\x12G\n" +
	"\x10CheckTransaction\x12\x18.fraud.FraudCheckRequest\x1a\x19.fraud.FraudCheckResponse\x12G\n" +
	"\fBlockAccount\x12\x1a.fraud.BlockAccountRequest\x1a\x1b.fraud.BlockAccountResponse\x12M\n" +
	"\x0eUnblockAccount\x12\x1c.fraud.UnblockAccountRequest\x1a\x1d.fraud.UnblockAccountResponse\x12S\n" +
	"\x10GetAccountStatus\x12\x1e.fraud.GetAccountStatusRequest\x1a\x1f.fraud.GetAccountStatusResponseB\x0fZ\rproto/fraudpbb\x06proto3"

var (
	file_proto_fraud_proto_rawDescOnce sync.Once
	file_proto_fraud_proto_rawDescData []byte
)

func file_proto_fraud_proto_rawDescGZIP() []byte {
	file_proto_fraud_proto_rawDescOnce.Do(func() {
		file_proto_fraud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fraud_proto_rawDesc), len(file_proto_fraud_proto_rawDesc)))
	})
	return file_proto_fraud_proto_rawDescData
}

var file_proto_fraud_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_fraud_proto_goTypes = []any{
	(*FraudCheckRequest)(nil),        // 0: fraud.FraudCheckRequest
	(*FraudCheckResponse)(nil),       // 1: fraud.FraudCheckResponse
	(*BlockAccountRequest)(nil),      // 2: fraud.BlockAccountRequest
	(*BlockAccountResponse)(nil),     // 3: fraud.BlockAccountResponse
	(*UnblockAccountRequest)(nil),    // 4: fraud.UnblockAccountRequest
	(*UnblockAccountResponse)(nil),   // 5: fraud.UnblockAccountResponse
	(*GetAccountStatusRequest)(nil),  // 6: fraud.GetAccountStatusRequest
	(*GetAccountStatusResponse)(nil), // 7: fraud.GetAccountStatusResponse
}
var file_proto_fraud_proto_depIdxs = []int32{
	0, // 0: fraud.FraudDetectionService.CheckTransaction:input_type -> fraud.FraudCheckRequest
	2, // 1: fraud.FraudDetectionService.BlockAccount:input_type -> fraud.BlockAccountRequest
	4, // 2: fraud.FraudDetectionService.UnblockAccount:input_type -> fraud.UnblockAccountRequest
	6, // 3: fraud.FraudDetectionService.GetAccountStatus:input_type -> fraud.GetAccountStatusRequest
	1, // 4: fraud.FraudDetectionService.CheckTransaction:output_type -> fraud.FraudCheckResponse
	3, // 5: fraud.FraudDetectionService.BlockAccount:output_type -> fraud.BlockAccountResponse
	5, // 6: fraud.FraudDetectionService.UnblockAccount:output_type -> fraud.UnblockAccountResponse
	7, // 7: fraud.FraudDetectionService.GetAccountStatus:output_type -> fraud.GetAccountStatusResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fraud_proto_init() }
func file_proto_fraud_proto_init() {
	if File_proto_fraud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fraud_proto_rawDesc), len(file_proto_fraud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fraud_proto_goTypes,
		DependencyIndexes: file_proto_fraud_proto_depIdxs,
		MessageInfos:      file_proto_fraud_proto_msgTypes,
	}.Build()
	File_proto_fraud_proto = out.File
	file_proto_fraud_proto_goTypes = nil
	file_proto_fraud_proto_depIdxs = nil
}
