// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/fraud.proto

package fraudpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FraudDetectionService_CheckTransaction_FullMethodName = "/fraud.FraudDetectionService/CheckTransaction"
	FraudDetectionService_BlockAccount_FullMethodName     = "/fraud.FraudDetectionService/BlockAccount"
	FraudDetectionService_UnblockAccount_FullMethodName   = "/fraud.FraudDetectionService/UnblockAccount"
	FraudDetectionService_GetAccountStatus_FullMethodName = "/fraud.FraudDetectionService/GetAccountStatus"
)

// FraudDetectionServiceClient is the client API for FraudDetectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FraudDetectionServiceClient interface {
	// CheckTransaction — called by transaction-service before every transfer
	CheckTransaction(ctx context.Context, in *FraudCheckRequest, opts ...grpc.CallOption) (*FraudCheckResponse, error)
	// BlockAccount — manual / parameterized block by operator
	BlockAccount(ctx context.Context, in *BlockAccountRequest, opts ...grpc.CallOption) (*BlockAccountResponse, error)
	// UnblockAccount — remove a manual block
	UnblockAccount(ctx context.Context, in *UnblockAccountRequest, opts ...grpc.CallOption) (*UnblockAccountResponse, error)
	// GetAccountStatus — inspect fraud / block state of an account
	GetAccountStatus(ctx context.Context, in *GetAccountStatusRequest, opts ...grpc.CallOption) (*GetAccountStatusResponse, error)
}

type fraudDetectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFraudDetectionServiceClient(cc grpc.ClientConnInterface) FraudDetectionServiceClient {
	return &fraudDetectionServiceClient{cc}
}

func (c *fraudDetectionServiceClient) CheckTransaction(ctx context.Context, in *FraudCheckRequest, opts ...grpc.CallOption) (*FraudCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FraudCheckResponse)
	err := c.cc.Invoke(ctx, FraudDetectionService_CheckTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fraudDetectionServiceClient) BlockAccount(ctx context.Context, in *BlockAccountRequest, opts ...grpc.CallOption) (*BlockAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockAccountResponse)
	err := c.cc.Invoke(ctx, FraudDetectionService_BlockAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fraudDetectionServiceClient) UnblockAccount(ctx context.Context, in *UnblockAccountRequest, opts ...grpc.CallOption) (*UnblockAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnblockAccountResponse)
	err := c.cc.Invoke(ctx, FraudDetectionService_UnblockAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fraudDetectionServiceClient) GetAccountStatus(ctx context.Context, in *GetAccountStatusRequest, opts ...grpc.CallOption) (*GetAccountStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountStatusResponse)
	err := c.cc.Invoke(ctx, FraudDetectionService_GetAccountStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FraudDetectionServiceServer is the server API for FraudDetectionService service.
// All implementations must embed UnimplementedFraudDetectionServiceServer
// for forward compatibility.
type FraudDetectionServiceServer interface {
	// CheckTransaction — called by transaction-service before every transfer
	CheckTransaction(context.Context, *FraudCheckRequest) (*FraudCheckResponse, error)
	// BlockAccount — manual / parameterized block by operator
	BlockAccount(context.Context, *BlockAccountRequest) (*BlockAccountResponse, error)
	// UnblockAccount — remove a manual block
	UnblockAccount(context.Context, *UnblockAccountRequest) (*UnblockAccountResponse, error)
	// GetAccountStatus — inspect fraud / block state of an account
	GetAccountStatus(context.Context, *GetAccountStatusRequest) (*GetAccountStatusResponse, error)
	mustEmbedUnimplementedFraudDetectionServiceServer()
}

// UnimplementedFraudDetectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFraudDetectionServiceServer struct{}

func (UnimplementedFraudDetectionServiceServer) CheckTransaction(context.Context, *FraudCheckRequest) (*FraudCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTransaction not implemented")
}
func (UnimplementedFraudDetectionServiceServer) BlockAccount(context.Context, *BlockAccountRequest) (*BlockAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlockAccount not implemented")
}
func (UnimplementedFraudDetectionServiceServer) UnblockAccount(context.Context, *UnblockAccountRequest) (*UnblockAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnblockAccount not implemented")
}
func (UnimplementedFraudDetectionServiceServer) GetAccountStatus(context.Context, *GetAccountStatusRequest) (*GetAccountStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountStatus not implemented")
}
func (UnimplementedFraudDetectionServiceServer) mustEmbedUnimplementedFraudDetectionServiceServer() {}
func (UnimplementedFraudDetectionServiceServer) testEmbeddedByValue()                               {}

// UnsafeFraudDetectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FraudDetectionServiceServer will
// result in compilation errors.
type UnsafeFraudDetectionServiceServer interface {
	mustEmbedUnimplementedFraudDetectionServiceServer()
}

func RegisterFraudDetectionServiceServer(s grpc.ServiceRegistrar, srv FraudDetectionServiceServer) {
	// If the following call panics, it indicates UnimplementedFraudDetectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FraudDetectionService_ServiceDesc, srv)
}

func _FraudDetectionService_CheckTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FraudCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudDetectionServiceServer).CheckTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraudDetectionService_CheckTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudDetectionServiceServer).CheckTransaction(ctx, req.(*FraudCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FraudDetectionService_BlockAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudDetectionServiceServer).BlockAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraudDetectionService_BlockAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudDetectionServiceServer).BlockAccount(ctx, req.(*BlockAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FraudDetectionService_UnblockAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudDetectionServiceServer).UnblockAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraudDetectionService_UnblockAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudDetectionServiceServer).UnblockAccount(ctx, req.(*UnblockAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FraudDetectionService_GetAccountStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudDetectionServiceServer).GetAccountStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraudDetectionService_GetAccountStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudDetectionServiceServer).GetAccountStatus(ctx, req.(*GetAccountStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FraudDetectionService_ServiceDesc is the grpc.ServiceDesc for FraudDetectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FraudDetectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fraud.FraudDetectionService",
	HandlerType: (*FraudDetectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckTransaction",
			Handler:    _FraudDetectionService_CheckTransaction_Handler,
		},
		{
			MethodName: "BlockAccount",
			Handler:    _FraudDetectionService_BlockAccount_Handler,
		},
		{
			MethodName: "UnblockAccount",
			Handler:    _FraudDetectionService_UnblockAccount_Handler,
		},
		{
			MethodName: "GetAccountStatus",
			Handler:    _FraudDetectionService_GetAccountStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fraud.proto",
}
