// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/fraud.proto

package fraudpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FraudCheckRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SourceAccountNo      string                 `protobuf:"bytes,1,opt,name=source_account_no,json=sourceAccountNo,proto3" json:"source_account_no,omitempty"`
	BeneficiaryAccountNo string                 `protobuf:"bytes,2,opt,name=beneficiary_account_no,json=beneficiaryAccountNo,proto3" json:"beneficiary_account_no,omitempty"`
	Amount               float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	PartnerReferenceNo   string                 `protobuf:"bytes,5,opt,name=partner_reference_no,json=partnerReferenceNo,proto3" json:"partner_reference_no,omitempty"`
	TransactionDate      string                 `protobuf:"bytes,6,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FraudCheckRequest) Reset() {
	*x = FraudCheckRequest{}
	mi := &file_proto_fraud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudCheckRequest) ProtoMessage() {}

func (x *FraudCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudCheckRequest.ProtoReflect.Descriptor instead.
func (*FraudCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_fraud_proto_rawDescGZIP(), []int{0}
}

func (x *FraudCheckRequest) GetSourceAccountNo() string {
	if x != nil {
		return x.SourceAccountNo
	}
	return ""
}

func (x *FraudCheckRequest) GetBeneficiaryAccountNo() string {
	if x != nil {
		return x.BeneficiaryAccountNo
	}
	return ""
}

func (x *FraudCheckRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FraudCheckRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FraudCheckRequest) GetPartnerReferenceNo() string {
	if x != nil {
		return x.PartnerReferenceNo
	}
	return ""
}

func (x *FraudCheckRequest) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

type FraudCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`                     // true = proceed, false = reject
	FraudCode     string                 `protobuf:"bytes,2,opt,name=fraud_code,json=fraudCode,proto3" json:"fraud_code,omitempty"` // "OK" | "BLOCKED_ACCOUNT" | "VELOCITY_BREACH" | ...
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RiskLevel     string                 `protobuf:"bytes,4,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"` // "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"
	Score         int32                  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`                         //
	Decision      string                 `protobuf:"bytes,6,opt,name=decision,proto3" json:"decision,omitempty"`                    // (ALLOW / REVIEW / REJECT)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudCheckResponse) Reset() {
	*x = FraudCheckResponse{}
	mi := &file_proto_fraud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudCheckResponse) ProtoMessage() {}

func (x *FraudCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudCheckResponse.ProtoReflect.Descriptor instead.
func (*FraudCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_fraud_proto_rawDescGZIP(), []int{1}
}

func (x *FraudCheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *FraudCheckResponse) GetFraudCode() string {
	if x != nil {
		return x.FraudCode
	}
	return ""
}

func (x *FraudCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FraudCheckResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *FraudCheckResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *FraudCheckResponse) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

var File_proto_fraud_proto protoreflect.FileDescriptor

const file_proto_fraud_proto_rawDesc = "" +
	"\n" +
	"\x11proto/fraud.proto\x12\x05fraud\"\x86\x02\n" +
	"\x11FraudCheckRequest\x12*\n" +
	"\x11source_account_no\x18\x01 \x01(\tR\x0fsourceAccountNo\x124\n" +
	"\x16beneficiary_account_no\x18\x02 \x01(\tR\x14beneficiaryAccountNo\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x120\n" +
	"\x14partner_reference_no\x18\x05 \x01(\tR\x12partnerReferenceNo\x12)\n" +
	"\x10transaction_date\x18\x06 \x01(\tR\x0ftransactionDate\"\xb8\x01\n" +
	"\x12FraudCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1d\n" +
	"\n" +
	"fraud_code\x18\x02 \x01(\tR\tfraudCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x04 \x01(\tR\triskLevel\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12\x1a\n" +
	"\bdecision\x18\x06 \x01(\tR\bdecision2`\n" +
	"\x15FraudDetectionService\x12G\n" +
	"\x10CheckTransaction\x12\x18.fraud.FraudCheckRequest\x1a\x19.fraud.FraudCheckResponseB\x0fZ\rproto/fraudpbb\x06proto3"

var (
	file_proto_fraud_proto_rawDescOnce sync.Once
	file_proto_fraud_proto_rawDescData []byte
)

func file_proto_fraud_proto_rawDescGZIP() []byte {
	file_proto_fraud_proto_rawDescOnce.Do(func() {
		file_proto_fraud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fraud_proto_rawDesc), len(file_proto_fraud_proto_rawDesc)))
	})
	return file_proto_fraud_proto_rawDescData
}

var file_proto_fraud_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_fraud_proto_goTypes = []any{
	(*FraudCheckRequest)(nil),  // 0: fraud.FraudCheckRequest
	(*FraudCheckResponse)(nil), // 1: fraud.FraudCheckResponse
}
var file_proto_fraud_proto_depIdxs = []int32{
	0, // 0: fraud.FraudDetectionService.CheckTransaction:input_type -> fraud.FraudCheckRequest
	1, // 1: fraud.FraudDetectionService.CheckTransaction:output_type -> fraud.FraudCheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fraud_proto_init() }
func file_proto_fraud_proto_init() {
	if File_proto_fraud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fraud_proto_rawDesc), len(file_proto_fraud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fraud_proto_goTypes,
		DependencyIndexes: file_proto_fraud_proto_depIdxs,
		MessageInfos:      file_proto_fraud_proto_msgTypes,
	}.Build()
	File_proto_fraud_proto = out.File
	file_proto_fraud_proto_goTypes = nil
	file_proto_fraud_proto_depIdxs = nil
}
